baseURL = 'https://chrisdeever.com/'
languageCode = 'en-us'
title = 'Chris Deever — Projects & Portfolio'
theme = 'blowfish'

enableGitInfo = true
enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
