[[main]]
  name = "Electronics"
  pageRef = "electronics"
  weight = 10

[[main]]
  name = "House"
  pageRef = "home-improvement"
  weight = 20

[[main]]
  name = "Car"
  pageRef = "car-projects"
  weight = 30

[[main]]
  name = "Maker"
  pageRef = "maker"
  weight = 35

[[main]]
  name = "Software"
  pageRef = "software"
  weight = 40

[[main]]
  name = "Reference"
  pageRef = "learning"
  weight = 60

[[main]]
  name = "About"
  pageRef = "about"
  weight = 70
